language: node_js
node_js:
  - "10"
cache:
  yarn: true
script:
  - git clone -b gh-pages -v --depth 1 https://github.com/ticlo/rc-dock.git ./www
  - yarn build-doc
  - yarn build-example
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: www
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
