name: Build github pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - uses: actions/checkout@v4 # checkout gh-pages into a different folder
        with:
          ref: gh-pages
          path: www
          fetch-depth: 1

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build www
        run: pnpm run build-www

      - name: Commit changes
        working-directory: ./www
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "noreply@ticlo.com"
          git add -A
          git commit -m "Deploy Github Action" || echo "No changes to commit"

      - name: Push changes
        run: git push
        working-directory: ./www
